name: Auto Assign Reviewers

on:
  workflow_dispatch:
    push:
      branches:
        - test-auto-assign-reviewers-*

env:
  TZ: 'Asia/Tokyo'

jobs:
  auto-assign-reviewers:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Create Pull Request
        run: |
          response=$(curl -X POST https://api.github.com/repos/${{ github.repository }}/pulls \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"base":"master","head":"${GITHUB_REF#refs/heads/}","title":"Auto Assign Reviewers Test"}')
          echo "Response: $response"

      # ビュアーを指定するために、GitHubのusernameを取得している
      # NOTE: https://docs.github.com/ja/rest/commits/commits?apiVersion=2022-11-28#list-commits
      - name: Get GitHub usernames from commit SHAs
        run: |
          git fetch origin develop
          commits=$(git log --pretty="%H" origin/develop..HEAD)

          ignore="genbaneko44"
          usernames=()

          for sha in $commits; do
            user=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          "https://api.github.com/repos/${{ github.repository }}/commits/$sha" | jq -r '.author.login')
            if [ "$user" ] && [ "$user" != "null" ] && [ "$user" != "$ignore" ] && ! [[ " ${usernames[*]} " =~ " $user " ]]; then
              usernames+=("$user")
              echo "Found GitHub user: $user"
            fi
          done

          echo "REVIEWERS=${usernames[*]}" >> $GITHUB_ENV

      # NOTE: https://docs.github.com/ja/rest/pulls/review-requests?apiVersion=2022-11-28
      - name: Assign reviewers to pull request
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "PR_NUMBER: $PR_NUMBER"
          FORMATTED_REVIEWERS=$(printf "\"%s\"\n" "${REVIEWERS[@]}" | sort -u | jq -sc .)

          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Content-Type: application/json" \
                -d "{\"reviewers\":$FORMATTED_REVIEWERS}" \
                "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/requested_reviewers"
