name: Auto Assign Reviewers

on: [pull_request, workflow_dispatch]

jobs:
  auto-assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get GitHub usernames from commit SHAs
        run: |
          git fetch origin main
          echo "Commits different from main:"
          commits=$(git log --pretty="%H" origin/main..HEAD | sort | uniq)
          usernames=()
          for sha in $commits; do
            user=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          "https://api.github.com/repos/${{ github.repository }}/commits/$sha" | jq -r '.author.login')
            if [ ! -z "$user" ] && [ "$user" != "null" ]; then
              usernames+=("$user")
              echo "Found GitHub user: $user"
            fi
          done
          echo "REVIEWERS=${usernames[*]}" >> $GITHUB_ENV

          - name: Assign reviewers to pull request
          run: |
            PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
            PR_AUTHOR=$(jq --raw-output .pull_request.user.login "$GITHUB_EVENT_PATH") # プルリクエスト作成者のログイン名を取得

            # REVIEWERS文字列を配列に変換し、プルリクエスト作成者を除外する
            IFS=' ' read -r -a REVIEWERS_ARRAY <<< "${REVIEWERS}"
            FILTERED_REVIEWERS_ARRAY=($(printf "%s\n" "${REVIEWERS_ARRAY[@]}" | grep -v "^$PR_AUTHOR$"))

            # 除外された配列からJSON配列を作成
            REVIEWERS_JSON=$(jq -nc '$ARGS.positional | map({login: .})' --args -- "${FILTERED_REVIEWERS_ARRAY[@]}")
            echo "REVIEWERS_JSON: $REVIEWERS_JSON"

            # レビュアーを割り当てるためのAPIコールを行う
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Content-Type: application/json" \
                 -d "{\"reviewers\":$REVIEWERS_JSON}" \
                 "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/requested_reviewers"
