name: Auto Assign Reviewers

on: [pull_request]

jobs:
  auto-assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get GitHub usernames from commit SHAs
        run: |
          git fetch origin main
          echo "Commits different from main:"
          commits=$(git log --pretty="%H" origin/main..HEAD | sort | uniq)
          usernames=()
          for sha in $commits; do
            user=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          "https://api.github.com/repos/${{ github.repository }}/commits/$sha" | jq -r '.author.login')
            if [ ! -z "$user" ] && [ "$user" != "null" ]; then
              usernames+=("$user")
              echo "Found GitHub user name: $user"
            fi
          done
          echo "REVIEWERS=${usernames[*]}" >> $GITHUB_ENV

      - name: Print PR Number
        run: echo "PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"

      - name: Assign reviewers to pull request
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          REVIEWERS_ARRAY=(${REVIEWERS})
          REVIEWERS_JSON=$(jq -n --argjson users "${REVIEWERS_ARRAY[@]}" '$users')
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d "{\"reviewers\":$REVIEWERS_JSON}" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/requested_reviewers"

      - name: repository name
        run: echo ${{ github.repository }}
