name: Auto Assign Reviewers

on: [pull_request, workflow_dispatch]

jobs:
  auto-assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get GitHub usernames from commit SHAs
        run: |
          git fetch origin main
          echo "Commits different from main:"
          commits=$(git log --pretty="%H" origin/main..HEAD | sort | uniq)
          usernames=()
          for sha in $commits; do
            user=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          "https://api.github.com/repos/${{ github.repository }}/commits/$sha" | jq -r '.author.login')
            if [ ! -z "$user" ] && [ "$user" != "null" ]; then
              usernames+=("$user")
              echo "Found GitHub user: $user"
            fi
          done
          echo "REVIEWERS=${usernames[*]}" >> $GITHUB_ENV

      - name: Assign reviewers to pull request
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          # REVIEWERS変数を文字列の配列に変換します。この例ではREVIEWERSはスペースで区切られた文字列と仮定しています。
          REVIEWERS_ARRAY=(${REVIEWERS})
          # jqを使用して、ログイン名のみを含む文字列の配列に変換します。
          REVIEWERS_JSON=$(jq -nc '[ $ARGS.positional[] ]' --args "${REVIEWERS_ARRAY[@]}")
          echo "REVIEWERS_JSON: $REVIEWERS_JSON"
          # APIコールを行い、レビュアーを割り当てます。
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Content-Type: application/json" \
                -d "{\"reviewers\":$REVIEWERS_JSON}" \
                "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/requested_reviewers"
